@{
    RootModule        = 'ManageEngine.ServiceDesk.OnPrem.Admin.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '99a35041-da1b-42e8-bcd7-5e5aab10f705'
    Author            = 'Griffeth Barker (github@griff.systems)'
    CompanyName       = ''
    Copyright         = '(c) 2026 Griffeth Barker'
    Description       = 'Admin module for the ManageEngine ServiceDesk Plus on-premises PowerShell module family. Provides cmdlets for managing users, org users, technicians, sites, regions, departments, support groups, categories, statuses, priorities, impacts, urgencies, levels, modes, items, priority matrix, announcements, and reminders.'
    PowerShellVersion = '7.0'

    ScriptsToProcess  = @(
        'Classes/001-SDPUtil.ps1'
        'Classes/002-SDPReference.ps1'
        'Classes/003-SDPOrgUser.ps1'
        'Classes/004-SDPUser.ps1'
        'Classes/005-SDPTechnician.ps1'
        'Classes/006-SDPSite.ps1'
        'Classes/007-SDPRegion.ps1'
        'Classes/008-SDPDepartment.ps1'
        'Classes/009-SDPSupportGroup.ps1'
        'Classes/010-SDPCategory.ps1'
        'Classes/011-SDPSubcategory.ps1'
        'Classes/012-SDPItem.ps1'
        'Classes/013-SDPAnnouncement.ps1'
        'Classes/014-SDPReminder.ps1'
    )

    RequiredModules   = @(
        @{ ModuleName = 'ManageEngine.ServiceDesk.OnPrem.Core'; ModuleVersion = '0.2.0' }
    )

    FunctionsToExport = @(
        'Get-SDPOrgUser'
        'New-SDPOrgUser'
        'Set-SDPOrgUser'
        'Remove-SDPOrgUser'
        'Get-SDPUser'
        'New-SDPUser'
        'Set-SDPUser'
        'Remove-SDPUser'
        'Convert-SDPUserToTechnician'
        'Get-SDPTechnician'
        'New-SDPTechnician'
        'Set-SDPTechnician'
        'Remove-SDPTechnician'
        'Convert-SDPTechnicianToUser'
        'Get-SDPRegion'
        'New-SDPRegion'
        'Set-SDPRegion'
        'Remove-SDPRegion'
        'Get-SDPSite'
        'New-SDPSite'
        'Set-SDPSite'
        'Remove-SDPSite'
        'Get-SDPDepartment'
        'New-SDPDepartment'
        'Set-SDPDepartment'
        'Remove-SDPDepartment'
        'Get-SDPSupportGroup'
        'New-SDPSupportGroup'
        'Set-SDPSupportGroup'
        'Remove-SDPSupportGroup'
        'Get-SDPCategory'
        'New-SDPCategory'
        'Set-SDPCategory'
        'Remove-SDPCategory'
        'Get-SDPSubcategory'
        'New-SDPSubcategory'
        'Set-SDPSubcategory'
        'Remove-SDPSubcategory'
        'Get-SDPStatus'
        'New-SDPStatus'
        'Set-SDPStatus'
        'Remove-SDPStatus'
        'Get-SDPPriority'
        'New-SDPPriority'
        'Set-SDPPriority'
        'Remove-SDPPriority'
        'Get-SDPUrgency'
        'New-SDPUrgency'
        'Set-SDPUrgency'
        'Remove-SDPUrgency'
        'Get-SDPImpact'
        'New-SDPImpact'
        'Set-SDPImpact'
        'Remove-SDPImpact'
        'Get-SDPLevel'
        'New-SDPLevel'
        'Set-SDPLevel'
        'Remove-SDPLevel'
        'Get-SDPMode'
        'New-SDPMode'
        'Set-SDPMode'
        'Remove-SDPMode'
        'Get-SDPItem'
        'New-SDPItem'
        'Set-SDPItem'
        'Remove-SDPItem'
        'Get-SDPPriorityMatrix'
        'New-SDPPriorityMatrix'
        'Set-SDPPriorityMatrix'
        'Remove-SDPPriorityMatrix'
        'Get-SDPPriorityMatrixOverride'
        'Set-SDPPriorityMatrixOverride'
        'Get-SDPAnnouncement'
        'New-SDPAnnouncement'
        'Set-SDPAnnouncement'
        'Remove-SDPAnnouncement'
        'Get-SDPReminder'
        'New-SDPReminder'
        'Set-SDPReminder'
        'Remove-SDPReminder'
        'Open-SDPReminder'
        'Close-SDPReminder'
    )

    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()

    PrivateData = @{
        PSData = @{
            Tags       = @('ManageEngine', 'ServiceDeskPlus', 'ITSM', 'REST', 'API', 'OnPremises', 'Admin', 'UserManagement')
            LicenseUri = 'https://github.com/griffeth-barker/ManageEngine.ServiceDesk.OnPrem/blob/main/LICENSE'
            ProjectUri = 'https://github.com/griffeth-barker/ManageEngine.ServiceDesk.OnPrem'
        }
    }
}
